# Generated by Django 4.2.1 on 2023-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=42)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=77)),
                ('address', models.CharField(max_length=42, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.DecimalField(decimal_places=0, max_digits=77)),
                ('holder', models.CharField(max_length=42)),
                ('address', models.CharField(max_length=42)),
            ],
        ),
    ]
